Sail needs special .env entries for docker
VSLCatena/mensa pull request #93
Opened 2022-10-14 14:56 UTC by Kipjr

2022-10-15 10:54 UTC, Kipjr commented
Forgot to update .env.example

2022-10-20 17:04 UTC, SubSide commented
Maybe we should eventually start commenting on the .env variables. Looking back to the .env variables I made they are confusing as heck 😅

2023-02-23 20:48 UTC, Kipjr commented
@SubSide bump

2023-05-20 17:08 UTC, SubSide approved these changes

2023-05-20 17:09 UTC, SubSide commented
Na de conflicts mag dit van mij wel gemerged worden :)

2023-05-20 17:16 UTC, SubSide commented
Nog een paar dingen missend bij deze MR zijn:
AuthServiceProvider roept registerPolicies aan: 
https://laravel.com/docs/10.x/upgrade#register-policies

Gaat de DB::raw goed bij orderedUsers in Mensa?
https://laravel.com/docs/10.x/upgrade#database-expressions

Ik zie nog een $dates voor komen in de code
https://laravel.com/docs/10.x/upgrade#model-dates-property


Dan zijn we als het goed is over :)

2023-05-20 17:16 UTC, SubSide requested changes
Nog een paar dingen missend bij deze MR zijn:
AuthServiceProvider roept registerPolicies aan:
https://laravel.com/docs/10.x/upgrade#register-policies

Gaat de DB::raw goed bij orderedUsers in Mensa?
https://laravel.com/docs/10.x/upgrade#database-expressions

Ik zie nog een $dates voor komen in de code
https://laravel.com/docs/10.x/upgrade#model-dates-property

Dan zijn we als het goed is over :)

2024-06-18 05:08 UTC, closed without merging